# Eureka 설정 (Gateway도 Discovery Client이므로 필요합니다)
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

# 라우팅 설정 (Index 번호를 사용하여 가독성 있게 정리)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user
spring.cloud.gateway.routes[0].predicates[0]=Path=/users/**
spring.cloud.gateway.routes[0].filters[0]=AuthorizationHeaderFilter

spring.cloud.gateway.routes[1].id=board-service
spring.cloud.gateway.routes[1].uri=lb://board
spring.cloud.gateway.routes[1].predicates[0]=Path=/boards/**
spring.cloud.gateway.routes[1].filters[0]=AuthorizationHeaderFilter

eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
