#spring.application.name=msa2
#spring.profiles.active=dev docker-compose.yml에 설정시 양쪽에서 설정하면 같은파일 설정한다고 에러남
server.port=8085

# 2. 데이터베이스 설정 (중요: 키 이름을 정확히 확인하세요)
spring.datasource.url=jdbc:mysql://board-db:3306/boarddb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Eureka 설정
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

management.endpoints.web.exposure.include=bus-refresh,refresh,health,info

#test acturator
spring.actuator=actuator test board
