server.port=9000
spring.application.name=config-server

spring.cloud.config.server.git.uri=git@github.com:foxrac/config-test.git
spring.cloud.config.server.git.ignore-local-ssh-settings=true
spring.cloud.config.server.git.private-key=\
  -----BEGIN RSA PRIVATE KEY-----\n\
MIIJJwIBAAKCAgEArAWRvdeUQpUvf8BTK+9xWu10U1rebBp+R2Tc90vhrIRC3z8U\n\
K6QQwzW84ZBdFGs4J97b3SKHbaRgX0ivH++6y+dSsN0H+xoM+IOYlLQTIcQ2ZPDS\n\
bqPWMUdp/c5TgKl6i5xLfejRm87P2zqw8hkB1mWDXx/61EbqY9iWDWqonnbGOagJ\n\
wI0uo2x7gwInxPlD3Flft4dbku3asXllPq0rf6aEw/ptRSRRw6pOCTPcZbT8yQNn\n\
bt7CWmvDz7wMihtjkRZMHbMnA3HT0vbrFV7+BLYbL3XjMhhNtdkaAbu2i3DqUKFj\n\
xTMF3nPtYyDk+GaGvLo23NxOCBnpSXI6/VJezzKjdh2n2qqvy7H66lbf6sy0YZJw\n\
c3N66QKJ/dIdIaBoJdUGODI14XgCyNW9h5Ztz9D8P0e6E7BEyBMAVbhwKtDdkfqC\n\
b1KPSFTTcxFxkyrPMKtezr768k96es/A9mmpHE6y7qt9Z0RHn2ySm130wreGPsRN\n\
n5mdkZUyVdE1jzqj0RH2I/oi2L0ipI4hmrs99XPjpwV1JYDXecVbEZ8cdS990ZvF\n\
i2hvwzwcnU2aS1/rXqr77NErWgZ3+g/0mf6rfbgI8D9wMwa8yS27bFu3ZfqCldZl\n\
3pjhqp9HZAIwY784XZaYVwQcyHeEVLkZFenV1GdNWaZKxuCVGEgxa6ZLDwUCAwEA\n\
AQKCAgBdyseVH/bZeugkGqP+n5ZJwpCbZj9B6AwUNz13pKsOWirv+D+yL8ln9mPf\n\
BMyLdo5uxsdQQiRfNrHJIiNCIX7S8HSYtFtGoQSTd4T5B1orHgWeceP6qV//DHYR\n\
Ca9jxoRnnLdYllm7Pz77xHt39QSYdk7zzccAeQ4RlKTz+cSoahBYnXN7xj64okyR\n\
uNogPtyuRxi2Q5o9eWy1OYBndRnzhsJ67I8plMz0B2Z3BAzWc6EkpLN/svt7O6jP\n\
GjQoFRjroaGsy+KosSaSr0isJVgRD42xCfDvfmrYjN/uNAAq9Uz825I/kjtP+Btl\n\
4iiV+6jZPBrvvzrYlfApuJvLRV8larlUTQ7ZbJz9Nm9IOJmr+Wf+iIvyIE4DNhgI\n\
Uns8p1YQ5ZoYQYrEsWVD49a1Eg/ycbzC8MhP7QYQd74vIH0S5HlU9S6wxEwpMpye\n\
C3zdmNlJwlPIKWHNsJuJwvIMUlC3lEeGVhlAfVNpLO6+kY4VzVetx0aV7oEIoJ2f\n\
2EgFJ2xr+WVw70m0KwX/8Dh4+bxh6xYEuH/kLyXkQnt7UChmVACQvXlR2hVOG/uv\n\
dvyKVy9cjNR+YdTxzFtZWypyKuadSEM5nE5Vo/rLeu7t5jR3953FNUgSGViu+FwN\n\
3bGaunlNg9YQ7iN6w+R5wwZ08f01xmjO/Rgo1q/2GJXeboChPQKCAQEA3lC7xceh\n\
R3wDk7eeS8+IjBP6jVBdyyZmmORLCHbBAtG1OuzkmjA9w361Tc/A8vkuNDqOE2I1\n\
2aYrvoe73wviit9yujjSvWb+v8qFX4W0irOLy6ITIHrFZe+djWWK0H54zvmEhNmD\n\
VYZ29dPWZx7NFNZm4tI9p26u9qSsiSNmFjyNs82rmkC9J4xckUu/Y5zDWTUnW0Zt\n\
agzGvkcvmU65TS5EG8bB3BFW6Jy0mRbUgERteaeA0VwpLiIZB4NNfgpCDhhTvqii\n\
1dk8Y0/xeqwQI5ZSlXtMYlLyUNmLBNSyiK0g9WN5t21jpuvPKcUXTLzVJ6nu8CX/\n\
gXvhsPkpN12ejwKCAQEAxhYGaukC4Oy2sRVZGOnLBZYUROQOxy9+x5cb562tQwFD\n\
phAzR01jQSD+I0Ynm7QpAv0qOBEbfc/IU7T/GpPoUZjd36p3KB45rAiO9EqlE7uJ\n\
2mrgvGW3pRuhK1F5c4v8uPOXUSm22d8YBs/EPQxBOO6YE4sI9VJC5vQT+N8E6qX0\n\
Yh/FPAkzJG8JJgFe+9w7SRIRmppg5Ii4ipugFeWHsmAjyo9wMWVoKzlGA74uH2is\n\
JG8OmL39+gyiQ2mzzR3rFM4ozcgAKndyA0A5Nexy8n/9n7gAz883pojpmvmyWC4H\n\
swM9SN7t5JFnJrbXA4CUVQT6CG5e0yHOAqIwns5DKwKCAQAvXK/EQPVhD1CLxdCZ\n\
ggsrHI6CUJ7KytGMvQYnNXWFLjwX46QIHULrRTFG9H28xc1MHzVpd8DVL4ueObiS\n\
miuXPmdouPZcl3aqUXD8mrWN3xZnOY4tmzo2r0e3eeyK4obGQW40B0rti4oIcSr6\n\
KRuz1sFwjS3JX9Eyhn6jcMEs95WQur5WTHh/1m1aHvMVO656cNKDpYtlzncAzpWb\n\
aaQch0DHUh62zZLgV5I6Ex0OfoV8J21QLPww8d63NQfrVDAiZJhiw/Z87Jzq43sk\n\
kUeW7U2Gvw/U2qr5An+VdeLbL1cYMCscItfaFd66nVyLYqdendtjmhTG9ydr1okr\n\
XGyNAoIBADXVeIsHpougaYo45gz6RP3QqtOKM2X4x3jQ3XmaXtMt/cec8YK4SnhB\n\
0i+d+le7n8W7LgUsyQ7pMGVndEkx11qNtAb8WgPiKwRREyDbRH/XYQCmOUuaTU2m\n\
86dFLj+z1MwjD4W0U4hktC/tuURqFzO0zEnLaHTblWkU/nSNj9WBoqgkQEMvsOF+\n\
97qHdtv2H3qdWYFt4VVavuSUpO4ugjF9JV0AnJogGC5fE2MjBX/tv5LrR8lFIUga\n\
tOKjUIU3U1NFMBu09i6UZbzycFnyV88F79S/eiEADPzKispegBSs9dS11ar/QyHy\n\
TllcKZU/FZEBmD5AWK8Cqe1XTOVr4x8CggEAG/G/LW1MOmWsgNnWQfsZWkYbGfUk\n\
8Syy5TSsQmAUC9gI2mMu+CLdn0XF9Jb99lxBF63354eUhgM+vGZU1g6TMc2M3G+5\n\
TWpeA0Q4w88Yvxx5LSK63pCh1xW9ZX7nZHklkxiQETTPQu7AuR1Rk6q25+fxKvPN\n\
e1xUSdiOxLXg1itQlggS3fD5/+YVdditS5hzHVN69+EQIsv2AVR+IkXtFUPONfg4\n\
wl6jBFP2q1QroOQJNQqBbavTTYZI5gvyuC69iwqFBvKF4+s2Je0bq9eFfK70leQR\n\
Bp44yqCOetMglLUfOxBB2ucaKh3DELKfBqLuGvrET7xezto2jjOytfYIMA==\n\
-----END RSA PRIVATE KEY-----
