#spring.application.name=msa2
#spring.profiles.active=dev docker-compose.yml에 설정시 양쪽에서 설정하면 같은파일 설정한다고 에러남
server.port=8085

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
