server.port=8081
grpc.server.port=9090

# 2. 데이터베이스 설정 (중요: 키 이름을 정확히 확인하세요)
spring.datasource.url=jdbc:mysql://user-db:3306/userdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Eureka 설정
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

eureka.instance.metadata-map.grpc.port=${grpc.server.port:9090}
grpc.server.reflection-service-enabled=true

management.endpoints.web.exposure.include=bus-refresh,refresh,health,info,env,circuitbreakers
#test acturator
spring.actuator=actuator test 03161302-1

# RabbitMQ 연결 정보
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.reply-timeout=3000ms

# Resilience4j Circuit Breaker 설정 (boardService 인스턴스)
resilience4j.circuitbreaker.instances.boardService.register-health-indicator=true
#최근 전적 범위
resilience4j.circuitbreaker.instances.boardService.sliding-window-size=10
#차단 기준(에러)  50%
resilience4j.circuitbreaker.instances.boardService.failure-rate-threshold=50
#차단 유지 시간
resilience4j.circuitbreaker.instances.boardService.wait-duration-in-open-state=10s
#복구 테스트 횟수 위의 10s 후 3번 시도
resilience4j.circuitbreaker.instances.boardService.permitted-number-of-calls-in-half-open-state=3
#차단 기준(지연) 30%
resilience4j.circuitbreaker.instances.boardService.slow-call-rate-threshold=30
#최소 5번해라
resilience4j.circuitbreaker.instances.boardService.minimum-number-of-calls=5
#지연 판단 기준
resilience4j.circuitbreaker.instances.boardService.slow-call-duration-threshold=2s
#차단 기준(지연) 30%
resilience4j.circuitbreaker.instances.bToC.slow-call-rate-threshold=30
#최소 5번해라
resilience4j.circuitbreaker.instances.bToC.minimum-number-of-calls=5
#지연 판단 기준
resilience4j.circuitbreaker.instances.bToC.slow-call-duration-threshold=2s

service-auth.url=http://auth-service:8090
service-board.url=http://msa-board-api-1:8085
feign.circuitbreaker.enabled=true
