server.port=8081
grpc.server.port=9090

# 2. 데이터베이스 설정 (중요: 키 이름을 정확히 확인하세요)
spring.datasource.url=jdbc:mysql://user-db:3306/userdb?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. JPA 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# 4. Eureka 설정
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/

eureka.instance.metadata-map.grpc.port=${grpc.server.port:9090}
grpc.server.reflection-service-enabled=true

management.endpoints.web.exposure.include=bus-refresh,refresh,health,info,env,circuitbreakers
#test acturator
spring.actuator=actuator test 03161302-1

# RabbitMQ 연결 정보
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.reply-timeout=3000ms

# Resilience4j Circuit Breaker 설정 (boardService 인스턴스)
resilience4j.circuitbreaker.instances.boardService.register-health-indicator=true
resilience4j.circuitbreaker.instances.boardService.sliding-window-size=10
resilience4j.circuitbreaker.instances.boardService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.boardService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.boardService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.boardService.slow-call-rate-threshold=100
resilience4j.circuitbreaker.instances.boardService.slow-call-duration-threshold=2s
